### ISSUE TITLE
move /docs to `gh-pages` branch and build docs with GitHub actions

### ISSUE THREAD

**Issue by brownag** [giswqs/whiteboxR#103]
It would be nice to have GitHub actions automatically build the HTML version of the manual so I don't have to remember to do it, or deal with committing it or conflicting issues with HTML source. It also would reduce the amount of content of the master branch overall as /docs folder could be removed entirely from master

The action can be triggered whenever any of the .Rd files are updated, so docs will always be up to date.

See for instance the pkgdown.yml file for {rgeedim}: https://github.com/brownag/rgeedim/blob/main/.github/workflows/pkgdown.yml

@giswqs: I  don't have access to the settings of the repo that could change what branch we serve the HTML manual from. How do you feel about this idea? Basically in settings I propose we change the current serving from /docs on master branch to the root / folder of a new gh-pages branch created with e.g. `git checkout --orphan gh-pages` / https://gist.github.com/ramnathv/2227408. The action would then commit to that branch whenever we update .Rd files in master.

**Comment by giswqs** [comment]
That's a good idea. Can you add the yml to create the gh-pages branch? I can easily change the repo settings once the gh-pages branch is created. GitHub repo does not seem to have to an option for setting a collaborator as a admin.

**Comment by giswqs** [comment]
Since I am no longer actively maintaining the package, I can transfer the ownership of the repo to you so that you can have full control of the repo. What do you think?

**Comment by brownag** [comment]
I created the gh-pages branch and created the .yml, which ran successfully, so the contents of the site should now be available at gh-pages branch root dir to be served.

https://github.com/giswqs/whiteboxR/commit/9e1a56ed7be826a88e072701d43ee9a71a826245

Now I just need to add the code to install WBT so that the examples will run and the like.

I feel like we need a little github organization or something for the various whitebox frontends/related repos. If it was just whiteboxR in there for now that would be fine... but I don't particularly want to take ownership of the repo or have the docs at https://humus.rocks/whiteboxR.

**Comment by brownag** [comment]
Wonderful. gh-pages is up, vignettes are running, good to go, thanks @giswqs

**Comment by giswqs** [comment]
@brownag Thank you for the great work! I can keep the repo ownership for now. We can create a GitHub organization later when we have more contributors.
