### ISSUE TITLE
fill depression output differs between whiteboxR and whitebox-tools

### ISSUE THREAD

**Issue by CCheCastaldo** [giswqs/whiteboxR#11]
Hi Wu, I am having an issue where the output from fill_depressions with whiteboxR differs significantly from FillDepressions with whitebox tools (with the latter looking correct, while the whiteboxR output has extremely large nonsensical values). I have attached some code comparing the fill depression tool using the [USGS Toutle River 2009 DEM](https://pubs.er.usgs.gov/publication/ds904), specifically the [10 M resolution DEM](https://pubs.usgs.gov/ds/0904/downloads/10m_DEM.zip). Is there some additional step I need to take when invoking whitebox tools from within R?

```R
library(raster); library(whitebox); library(dplyr)

dem_10m <- raster("../DEM/10m_DEM/msh2009dem10/w001001.adf") 
wbt <- "~/whitebox-tools/target/release/whitebox_tools"

writeRaster(dem_10m, "../TemporaryObjects/dem.tif", overwrite = TRUE, 
  options = c("COMPRESS=NONE"))`

fill_depressions(dem = "../TemporaryObjects/dem.tif", output = "../TemporaryObjects/dem_filled1.tif", fix_flats = FALSE) 

system(paste0(wbt, " -r=FillDepressions --wd='../TemporaryObjects/' -i='dem.tif' -o='dem_filled2.tif'"))

dem_filled1 <- raster("../TemporaryObjects/dem_filled1.tif")
dem_filled2 <- raster("../TemporaryObjects/dem_filled2.tif")
compareRaster(dem_filled1, dem_filled2, stopiffalse = FALSE)
all.equal(dem_filled1, dem_filled2)
wbR_cells <- data.frame(getValues(dem_filled1))
wbt_cells <- data.frame(getValues(dem_filled2))
temp <- cbind(wbR_cells, wbt_cells) 
names(temp) <- c("wbR", "wbt")
temp2 <- temp %>% filter(wbR!=wbt)
```

```R
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.0.1  whitebox_0.4.0 raster_2.9-5   sp_1.3-1      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       lattice_0.20-38  codetools_0.2-16 crayon_1.3.4     assertthat_0.2.1 grid_3.5.3       R6_2.4.0         magrittr_1.5     pillar_1.3.1    
[10] rlang_0.3.2      rstudioapi_0.10  rgdal_1.4-3      tools_3.5.3      glue_1.3.1       purrr_0.3.2      yaml_2.2.0       compiler_3.5.3   pkgconfig_2.0.2 
[19] tidyselect_0.2.5 tibble_2.1.1   
```

Thanks for any advice. I appreciate all your hard work on this package.

Chris

**Comment by giswqs** [comment]
The whiteboxR package uses the WBT executable of WhiteboxTools v0.16.0 released on May 24, 2019. Dr. John Lindsay (@jblindsay) has made some updates to whitebox-tools since then. I am not sure if he updates the Fill Depression tool. A temporary fix for you would be to replace the WBT executable for whiteboxR (e.g., `~/R/x86_64-pc-linux-gnu-library/3.5/whitebox/WBT/`) with the new executable (e.g., `~/whitebox-tools/target/release/whitebox_tools`), then rerun the R script to see if they produce the same results.

**Comment by CCheCastaldo** [comment]
Thanks for your help. I installed whiteboxR from your GitHub repo and afterwards had to run `wb_init()`, which automatically downloaded and installed a WBT binary to: 

`/Library/Frameworks/R.framework/Versions/3.5/Resources/library/whitebox/WBT/whitebox_tools`

I can see this by running `wbt_exe_path()` in R. I then replaced the `whitebox_tools` executable in this directory with the one I had compiled from John Lindsay's whitebox-tools, using the cargo package in rust. However, when I rerun the code the same differences persist  between the filled rasters, even though both `dem_filled1` and `dem_filled2` are now made using the identical WBT executable. I can always work around this problem using the system calls to whitebox_tools from R but I just wanted to point out this weirdness.

**Comment by jblindsay** [comment]
Earlier today I uploaded a change to both the FillDepressions and BreachDepressions tools to output 64-bit floating-point rasters. This fixes a bug in which the small number that is used to fix flat points is so small that if the data are stored in the more usual 32-bit format, strange things can happen. If you've compiled your version of WhiteboxTools very recently, this likely accounts for the difference.

**Comment by CCheCastaldo** [comment]
I compiled WhiteboxTools about two weeks ago and noticed the difference between the command line FillDepression and whiteboxR fill_depression right away. Also, when I replace the WBT executable that is installed with whiteboxR with the rust executable from WhiteboxTools (which should make the outputs identical if the cause is the bug fix you mention) the differences persists. So I am not sure that your recent update in the last 24 hours is the cause. Here is some output from the raw DEM (raw), the filled DEM with whiteboxR after updating the WBT exectuable (wbR), and the filled DEM with the command line whitebox tools (wbt):

```R
        raw     wbR      wbt
1  443.0913 3.0e+13 443.3810
2  450.4977 6.0e+13 450.5378
3  403.7487 2.8e+14 404.1165
4  328.6358 1.8e+14 330.1462
5  329.5071 1.7e+14 330.1462
6  329.2334 1.7e+14 330.1462
7  328.9503 1.7e+14 330.1462
8  329.1920 1.8e+14 330.1462
9  329.2427 1.8e+14 330.1462
10 328.8381 1.8e+14 330.1462
```

**Comment by giswqs** [comment]
@CCheCastaldo Thanks for reporting this issue! I found that this is a major bug of the R package. Some logical parameters were not passed correctly to the WBT executable. In your case, the `--fix_flats` flag was always passed to the executable even though you set `fix_flats = FALSE` in the R function. I have committed [code](https://github.com/giswqs/whiteboxR/commit/68d897a30fd101de162f229f012eeb92b61dcd18) to fix this. Please install the latest version and try your R script again. It should now produce identical results. 

-  `devtools::install_github("giswqs/whiteboxR")`

**Comment by CCheCastaldo** [comment]
Thanks so much for fixing this bug so quickly.
