### ISSUE TITLE
Request: Reduce conflicts with base R functions

### ISSUE THREAD

**Issue by tylermorganwall** [giswqs/whiteboxR#13]
Hi,

I am prepping a masterclass for GIS students and have been using the whitebox package to help clean, manipulate, and analyze lidar and topographic data. I have been very impressed by the breadth and depth of functionality that the package provides. The functions provided by the underlying whitebox package provides much needed capability to the R GIS ecosystem.

I do have some suggestions, however, in order to have the package play more nicely with the R package ecosystem. Generally, masking R functions provided by the base/stats/graphics package is a poor practice when naming your package's functions. Currently, whitebox overwrites a significant number of these functions, which can confuse users since many of these functions are used in logic control and general non-whitebox-specific programming (min, max, round).

```r
> library(whitebox)
Attaching package: ‘whitebox’

The following objects are masked from ‘package:stats’:

    anova, power, profile

The following object is masked from ‘package:graphics’:

    clip

The following objects are masked from ‘package:base’:

    atan2, cos, cosh, exp, floor, intersect, log10, log2, max, min, round, sin, sinh, sink, tan, tanh, truncate, union, xor

```

Since these functions are interfacing with the whitebox library, I would suggest making that clear by adding a prefix such as `wb_` or `wbt_` to the whitebox specific versions. This would both make it clear to the user which version of the function is being called, as well as improve the experience of users using an IDE that supports autocompletion, since entering the prefix would then bring up all the functions provided specifically by the whitebox package (a practice well-demonstrated by the `stringr` package). 

Best regards,
Tyler

**Comment by giswqs** [comment]
@tylermorganwall Thank you for your suggestion! I have added prefix `wbt_` to all functions. Please reinstall the package and let me know if you find any bugs. Thanks. 

```
devtools::install_github("giswqs/whiteboxR")
```

**Comment by tylermorganwall** [comment]
Awesome, thanks for the quick response!
