### ISSUE TITLE
Cannot set working directory in Whitebox package in R

### ISSUE THREAD

**Issue by mismaielahmed** [giswqs/whiteboxR#17]
The working directory cannot be set when using the package in R.
There is a function to set the working directory in the python library and even when running from terminal/cmd.
Is there any function to do this in R?

**Comment by giswqs** [comment]
You can set the Working Directory in RStudio, then you should be able to use relative file paths when calling WBT functions.

![](http://www.sthda.com/sthda/RDoc/images/rstudio-change-working-directory.png)

**Comment by mismaielahmed** [comment]
I am doing that already. But when I use the whiteboxtools from the cmd/terminal, I can explicitly define the working directory (using --wd command) and all output is written in that directory.
It would be useful if such a command exists in the R package because it is quite annoying to use the relative path each time you need to run a function.
Would that be possible?

**Comment by giswqs** [comment]
Yes, I believe it is possible. Let me look into it.

**Comment by giswqs** [comment]
I have added a `wd` parameter for all tools. Please install the latest version from GitHub. It seems working properly on my end. Please test it and let me know if you have any issues. 

```
if (!require(devtools)) install.packages('devtools')
devtools::install_github("giswqs/whiteboxR")
```

![](https://i.imgur.com/MVCl6AE.png)

**Comment by mismaielahmed** [comment]
It works fine.
Thank you so much for your response and efforts.
