### ISSUE TITLE
Math tools with logical operator names

### ISSUE THREAD

**Issue by jblindsay** [giswqs/whiteboxR#2]
Note that the Python interface for WhiteboxTools needed to violate the snake-case convention for function names for the Whitebox tools with logical operators (And, Not, Or) because Python uses these as keywords (and, not, or). I believe *R* uses the more conventional form for logical operators (&&, !, ||) and so there is no potential for name collisions. Can we change these function names to their snake-case equivalents?

**Comment by giswqs** [comment]
Thank you for pointing this out! I have changed these three logical functions to snake case. GitHub repo has been updated. The change will be reflected in our next CRAN release, as the [CRAN policy](http://r-pkgs.had.co.nz/release.html#cran-policies) suggests a new version once every 1-2 months at most.
