### ISSUE TITLE
Examples in WhiteboxR (Not issue)

### ISSUE THREAD

**Issue by ns-1m** [giswqs/whiteboxR#22]
Hi,

I am glad that there is a support for R for Whitebox.

However, I found out the help for Whitebox does not include examples how to use the usage especially in LiDAR Tools.

It would have been nice if there is examples how to use the "usage".

Thanks.

Noli

P.S. lidR package has very good examples. It has a lot of LiDAR data as well.

Probably, LiDAR data from lidR can be used for the examples how to use the usage for WhiteboxR.

**Comment by giswqs** [comment]
Check out the [LiDAR tutorial](https://jblindsay.github.io/wbt_book/tutorials/lidar.html) from the [WhiteboxTools User Manual](https://jblindsay.github.io/wbt_book).

**Comment by ns-1m** [comment]
Any other examples in using Whitebox in R aside from this https://jblindsay.github.io/wbt_book/r_interface.html 

~~~
library(whitebox)

# Set input raster DEM file
dem <- system.file("extdata", "DEM.tif", package="whitebox")

# Run tools
feature_preserving_denoise(dem, "./smoothed.tif", filter=9)
breach_depressions("./smoothed.tif", "./breached.tif")
d_inf_flow_accumulation(dem, "./flow_accum.tif", verbose_mode=FALSE)

~~~~

It seems only Python and Command-line in Tutorial and User Manual.

How to see Whitebox R Tutorials.

Thanks.
