### ISSUE TITLE
Setting raster compression

### ISSUE THREAD

**Issue by laurencehawker** [giswqs/whiteboxR#23]
Hi,

I was wondering how/if it is possible to set raster compression? I believe in the Python version there is a ``wbt.set_compress_rasters(True)`` option.
I have been using the mean_filter tool which has been great but the output rasters are huge (e.g. 1.4Gb for a 20,000x20,000 raster which results in a raster full of nodata values). This is for a Float32 raster with TIFFTAG_SOFTWARE=WhiteboxTools

```
 WhiteboxTools v1.4.0 by Dr. John B. Lindsay (c) 2017-2020"
R version 4.0.0 (2020-04-24)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
```

**Comment by giswqs** [comment]
Thank you for your suggestion. I have added the `compress_rasters` flag to every tool. Please test it and let me know how it works. Thanks. 

```
wbt_mean_filter(
  input,
  output,
  filterx = 3,
  filtery = 3,
  wd = NULL,
  verbose_mode = FALSE,
  compress_rasters = FALSE
)
```

https://giswqs.github.io/whiteboxR/reference/wbt_mean_filter.html

**Comment by laurencehawker** [comment]
Hi,
``compress_rasters`` works well. Thanks for the addition!
I am still having problems with wbt_mean_filter returning all NoData values for my 20kx20k raster. wbt_median_filter works so possibly a memory issue. I can open a separate issue if need be.

**Comment by giswqs** [comment]
Reading and writing data are handled by the backend [whitebox-tools](https://github.com/jblindsay/whitebox-tools). You can open an issue [here](https://github.com/jblindsay/whitebox-tools/issues) if needed.
