### ISSUE TITLE
Where is my fault?

### ISSUE THREAD

**Issue by akersayin** [giswqs/whiteboxR#25]
I try to learn WhiteBox usage in R. But I cannot succeed even an easy analysis like below. So, what is my fault?

My codes,

library(sp)
library(raster)
library(whitebox)
dem <- raster("dem.tif")
output <- "D:/R/WTB/slope.tif"
slope2 <- wbt_slope(dem, output, units = "degrees")

Results,
> slope2 <- wbt_slope(dem, output, units = "degrees")
Warning message:
In system(args2, intern = TRUE) :
  'C:/Users/KEMAL/Documents/R/win-library/4.0/whitebox/WBT/whitebox_tools.exe --run=slope  --dem=raster(ncol=4897, nrow=5348, xmn=611459.160047657, xmx=660429.160047657, ymn=4486185.69062748, ymx=4539665.69062748, crs='+proj=utm +zone=37 +datum=WGS84 +units=m +no_defs') --output=D:/R/WTB/slope.tif --units=degrees -v' komutunu çalıştırırken 101 durumu oluştu

**Comment by giswqs** [comment]
Input files to wbt should be file paths to your data, not raster("dem.tif"). 

```
library(whitebox)

# Set input raster DEM file
dem <- system.file("extdata", "DEM.tif", package="whitebox")

# Run tools
wbt_feature_preserving_smoothing(dem, "./smoothed.tif", filter=9, verbose_mode = TRUE)
wbt_breach_depressions("./smoothed.tif", "./breached.tif")
wbt_d_inf_flow_accumulation(dem, "./flow_accum.tif")
```

**Comment by akersayin** [comment]
Dear @giswqs ,
I passed the first step. :)
I created "slope" and "flow accumulation" data to "stream power index" analysis. But now, I got this error. 

My codes, 
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package = "whitebox")

slope <- wbt_slope(dem, "./slope.tif", units = "degree")

sca <- wbt_d8_flow_accumulation(dem, "./fa.tif", out_type = "specific contributing area", log=FALSE, clip=FALSE, pntr =FALSE, esri_pntr = FALSE, wd=NULL, verbose_mode = FALSE)

spi <- wbt_stream_power_index(sca, slope, "./spi", exponent = 1, wd=NULL, verbose_mode = FALSE)


Results, 
> slope <- wbt_slope(dem, "./slope.tif", units = "degree")
> sca <- wbt_d8_flow_accumulation(dem, "./fa.tif", out_type = "specific contributing area", log=FALSE, clip=FALSE, pntr =FALSE, esri_pntr = FALSE, wd=NULL, verbose_mode = FALSE)
> spi <- wbt_stream_power_index(fa, slope, "./spi", exponent = 1, wd=NULL, verbose_mode = FALSE)
Warning message:
In system(args2, intern = TRUE) :
  'C:/Users/KEMAL/Documents/R/win-library/4.0/whitebox/WBT/whitebox_tools.exe --run=stream_power_index  --sca=d8_flow_accumulation - ********************************************************************************** --slope=slope - Elapsed Time (excluding I/O): 0.121s --output=./spi --exponent=1 -v' komutunu çalıştırırken 101 durumu oluştu

Also, I put a screen shot. 
![SS](https://user-images.githubusercontent.com/74820648/99911506-eb422880-2d05-11eb-8410-384bf07f8ca8.JPG)

**Comment by giswqs** [comment]
Do NOT assign tool output to variables. All WBT tools are independent. 

```
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package = "whitebox")
slope <- "./slope.tif"
sca <- "./fa.tif"
spi <- "./spi.tif"

wbt_slope(dem, slope, units = "degree")

wbt_d8_flow_accumulation(dem, sca, out_type = "specific contributing area", log=FALSE, clip=FALSE, pntr =FALSE, esri_pntr = FALSE, wd=NULL, verbose_mode = FALSE)

wbt_stream_power_index(sca, slope,  spi, exponent = 1, wd=NULL, verbose_mode = FALSE)

```

**Comment by akersayin** [comment]
Dear @giswqs ,
Now everything worked without any error and I got Stream Power Index result map. 
I'm grateful for your detailed replies. Thank you so much.
