### ISSUE TITLE
Can whiteboxR work with raster::raster objects or only with tiffs stored on disk?

### ISSUE THREAD

**Issue by alherca73** [giswqs/whiteboxR#26]
Hello. I would like to use whiteboxR for a ton of watershed delineations. I've got pretty much all of the Western US DEMs but unfortunately they are in ESRI GRID format. I can read this into memory in R using raster::raster. 

Is there a way to utilize raster::raster object with WhiteBoxR tools?

Thanks!

**Comment by giswqs** [comment]
Unfortunately, the answer is NO. The WhiteboxTools library can currently support read/writing raster data in Whitebox GAT, GeoTIFF, ESRI (ArcGIS) ASCII and binary (.flt & .hdr), GRASS GIS, Idrisi, SAGA GIS (binary and ASCII), and Surfer 7 data formats. See https://github.com/jblindsay/whitebox-tools

**Comment by alherca73** [comment]
Oh Ok. Thanks for clarifying!
