### ISSUE TITLE
whiteboxR and R objects

### ISSUE THREAD

**Issue by chljl** [giswqs/whiteboxR#27]
I am trying to use the whiteboxR package for some geospatial analysis in R. I found that the tool seems only to use hard drive files as input and output in its functions, but not using regular R objects. Can I use, for example, a raster object in R as the input for whiteboxR functions , and output the result directly to R objects rather than frequently reading and writing data from the hard drive?  Thank you.

**Comment by giswqs** [comment]
Unfortunately, the answer is NO. See Dr. John Lindsay's (@jblindsay) explanation [here](https://github.com/jblindsay/whitebox-tools/issues/52#issuecomment-551162422) and [here](https://github.com/jblindsay/whitebox-tools/issues/68#issuecomment-585794867).
