### ISSUE TITLE
Add "dinf" argument to wbt_downslope_distance_to_stream

### ISSUE THREAD

**Issue by bkielstr** [giswqs/whiteboxR#31]
Hi there, 

It looks like WhiteboxTools has a "dinf = TRUE/FALSE" flag but the R implementation does not. 

Would it be possible to add this?

https://jblindsay.github.io/wbt_book/available_tools/hydrological_analysis.html?highlight=dinf#downslopedistancetostream

**Comment by giswqs** [comment]
The `dinf` argumment was recently added by @jblindsay. It won't be available for the R frontend until the next release. You can compile the WBT binary from source and modify the R function if you want to use it now. See the instructions [here](https://github.com/jblindsay/whitebox-tools#building-from-source-code).  

https://github.com/jblindsay/whitebox-tools/commit/755c9c7cc7dc0e019be892c0a04ef0d05b0894e7

![image](https://user-images.githubusercontent.com/5016453/110649946-19018f00-8188-11eb-8d23-0dbf1a9e2e8c.png)

**Comment by bkielstr** [comment]
Perfect, thank you!

**Comment by bkielstr** [comment]
Shouldn't have closed this issue unless you want to.

**Comment by giswqs** [comment]
You can close this issue if you want to. This issue should be fixed automatically in the next release.
