### ISSUE TITLE
Error in system(args2, intern = TRUE) : 'C:/Program' not found

### ISSUE THREAD

**Issue by ashishshankar0894** [giswqs/whiteboxR#32]
This is the same lines which are on the description.

`library(whitebox)`
`dem <- system.file("extdata", "DEM.tif", package="whitebox")`
`wbt_feature_preserving_smoothing(dem, "./output.tif", filter=9, verbose_mode = TRUE)`

Getting an error
`Error in system(args2, intern = TRUE) : 'C:/Program' not found`

**Comment by giswqs** [comment]
I just tested the sample code on both Windows and Linux, and it works fine.

**Comment by giswqs** [comment]
This bug has been fixed. Please install the latest version from GitHub. This bug was caused by the space (e.g., `"C:/Program Files (x86)"`) in the WBT exe file path. 

```
devtools::install_github("giswqs/whiteboxR")
```
