### ISSUE TITLE
Error in system(args2, intern = TRUE) : 

### ISSUE THREAD

**Issue by oziashub** [giswqs/whiteboxR#33]
I have installed the R front end of whiteboxtool and run the code below but got the error below. I read online but could not find any consistant answer. I am using a window 10 system

> library(whitebox)
> dem <- system.file("extdata", "DEM.tif", package="whitebox")
> output <- file.path(getwd(), "output.tif")
> whitebox::wbt_impoundment_size_index(dem, damlength=40,output)

Error in system(args2, intern = TRUE) : 
  '\\storage.slu.se/Home$/ozho0001/My' not found

**Comment by giswqs** [comment]
Run the sample code below and see what you get. 

```
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package="whitebox")
wbt_feature_preserving_smoothing(dem, "./smoothed.tif", filter=9, verbose_mode = TRUE)
```

**Comment by oziashub** [comment]
Thanks for the reply. I still got the same error. I change to another computer with window but still got the same massage. 
Error in system(args2, intern = TRUE) : 
  '\\storage.slu.se/Home$/ozho0001/My' not found

**Comment by giswqs** [comment]
Are you saving data to a network drive? Try saving data to your local drive with spaces in the file path.

**Comment by oziashub** [comment]
May a local problem on my side. No matter the path local or to the drive I still got the message.

**Comment by giswqs** [comment]
What is the file path to your R packages installation directory?

**Comment by giswqs** [comment]
Apparently, that file path is not on your local computer. Try to install whiteboxR on your local computer to run it.

**Comment by oziashub** [comment]
Thanks. I will give it a try. I really appreciate your help.

**Comment by giswqs** [comment]
You can also try it with Google Colab
https://colab.research.google.com/drive/16SJKfbDQVuaanOI7oA7vybOIWaKt5EFZ?usp=sharing

**Comment by oziashub** [comment]
Thanks. It is now working fine. The issue was related whitebox not accessing my local path.
