### ISSUE TITLE
Running batch files for impoundment index issue with output

### ISSUE THREAD

**Issue by oziashub** [giswqs/whiteboxR#34]
Hi. I am using whitetboxtool in R to compute impoundment index for 1000 tiles of rasters. Since it will be too cumbersome to do it individually I have opted for writing a batch code to do it in parallel as shown in the code below. 

library(raster)
library(foreach)
library(doParallel)

###set my working directory
setwd("path")

#setup parallel backend to use many processors
cores=detectCores()
cl <- makeCluster(cores[1]-1) 
registerDoParallel(cl)

tiles<-list.files(path = "mypath", pattern = '*tif$', full.names=T)
foreach(i=1:length(tiles),.packages = "whitebox") %dopar% 
{
Index<-wbt_impoundment_size_index(
  tiles[i],
  damlength=40, 
  out_type = "mean depth",
  output = paste0("E:/Gotland_Ditch/ImpIndex", 'T_',i,'.tif'))
}

#stop cluster
stopCluster(cl)

However I got the following error: "Error in summary.connection(connection):invalid connection". when I replace i=1 and run only the wbt_impoundment_size_index it works fine. I think it has to do with the output, writing each file at a time as it is computed. I will appreciate any help.

**Comment by giswqs** [comment]
I have not used R for a while and I am not familiar with the doParallel package. Did you try the regular looping without doParallel?

**Comment by oziashub** [comment]
Hi. Thanks for the feedback. Yes the regular looping as coded 

 below works fine. But only one core is used and I would preferred to run the code in parallel because of the high number of tiles. 

for(i in 1:length(tiles)){
  wbt_impoundment_size_index(
    tiles[i],
    damlength=40, 
    out_type = "mean depth",
    output = paste0("path", 'T_',i,'.tif'))
}

**Comment by giswqs** [comment]
If the regular looping works fine, then the problem is not on the whitebox end. Try your parallel routine without whitebox and make sure it works as expected, then you can integrate whitebox into your routine.
