### ISSUE TITLE
Downloading Issue from GITHUB

### ISSUE THREAD

**Issue by sabangroo** [giswqs/whiteboxR#35]
I tried to install whiteboxR via Github, but it fails
Please look into the matter.

`devtools::install_github("giswqs/whiteboxR")`

> Downloading GitHub repo giswqs/whiteboxR@HEAD
> Error: Failed to install 'whitebox' from GitHub:
System command 'Rcmd.exe' failed, exit status: -1, stdout + stderr empty

**Comment by giswqs** [comment]
What operating system are you using? I just tested the installation on Windows, and it worked fine. Try installing from R-Forge. 

```
install.packages("whitebox", repos="http://R-Forge.R-project.org")
```

![image](https://user-images.githubusercontent.com/5016453/119759183-cf1a7200-be75-11eb-8a9c-d0414b30a908.png)

**Comment by sabangroo** [comment]
I am using windows OS.
I tried many times to download it from`devtools::install_github("giswqs/whiteboxR")`
But I am getting the same error
![111](https://user-images.githubusercontent.com/69730776/119760078-f9e0e680-bec6-11eb-9cf9-1c7eca7189b5.JPG)

Installation works from `install.packages("whitebox", repos="http://R-Forge.R-project.org")`
But functions are not working, see below
![2222](https://user-images.githubusercontent.com/69730776/119760225-3f051880-bec7-11eb-8c4c-5cf55b807013.JPG)

**Comment by giswqs** [comment]
Try it with Google Colab. 

https://colab.research.google.com/drive/1V7ID9AWz_kI8S88Z6nZxzPJz3G3lM6Or?usp=sharing

**Comment by brownag** [comment]
@sabangroo I am curious if you are still have trouble installing from GitHub with latest version. Try using the {remotes} package which has the `install_github()` function that {devtools} uses. 
```
install.packages("remotes")
```

When using {remotes} I most often have issues with installing dependencies or error in build. 
You can try running `remotes::install_github("giswqs/whiteboxR", dependencies=FALSE, build=FALSE)` to try and limit some possible sources of error.

**Comment by sabangroo** [comment]
> @sabangroo I am curious if you are still have trouble installing from GitHub with latest version. Try using the {remotes} package which has the `install_github()` function that {devtools} uses.
> 
> ```
> install.packages("remotes")
> ```
> 
> When using {remotes} I most often have issues with installing dependencies or error in build.
> You can try running `remotes::install_github("giswqs/whiteboxR", dependencies=FALSE, build=FALSE)` to try and limit some possible sources of error.

**Comment by sabangroo** [comment]
Thanks @brownag for the reply
I tried to install.packages("remotes"), But I am still unable to install it.

remotes::install_github("giswqs/whiteboxR", dependencies=FALSE, build=FALSE)
Downloading GitHub repo giswqs/whiteboxR@HEAD
Installing package into ‘C:/Users/shalzsab/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/shalzsab/AppData/Local/Temp/Rtmp46Lpmx/remotes5bc031792f9/giswqs-whiteboxR-7ea9e20’ had non-zero exit status

**Comment by brownag** [comment]
@sabangroo

Interesting. I am leaning towards thinking this is some sort of a configuration issue with your computer as we have a CI running for Windows and it has no issues with install. My work computer is a Windows machine that I have limited privileges on and I have no issues installing from GitHub.

I have three final things I can suggest:
 - Is there a firewall or antivirus software that may be interfering with download, saving to temp folder, copying files to library etc?
 - Does installing other packages using `remotes::install_github()` work? Is it just "giswqs/whiteboxR" that is failing?
 - Can you install the package if you use git clone the repository, or download it as a [ZIP](https://github.com/giswqs/whiteboxR/archive/refs/heads/master.zip), then call `remotes::install_local()` in the package folder (i.e. bypassing the download step)

**Comment by sabangroo** [comment]
@brownag Yes, you are right. I could successfully install it on my other machine. It was definitely a  configuration issue, after some troubleshooting, I could manage to install it smoothly. 
Thanks for your help

**Comment by brownag** [comment]
Excellent!
