### ISSUE TITLE
Error in system(args, intern = TRUE) : 'C:/Users/PROJETO' not found

### ISSUE THREAD

**Issue by tcalegario** [giswqs/whiteboxR#38]
Dear Qiusheng Wu,

I'm trying to access whitebox, but I can't due a to "blank space" in my folder user name.

'C:/Users/PROJETO RENOVA/...

> wbt_fill_depressions("E:/rgee/dados/demP.tif", "E:/rgee/dados/demP_teste.tif")
> Error in system(args2, intern = TRUE) : 'C:/Users/PROJETO' not found

Do you think there is a way to solve it instead of changing my username folder?

Thanks for developing this package.

In another machine that I use ran each tack in less than 1 second.

Best wishes.

**Comment by giswqs** [comment]
When and how did you install whiteboxR? I believe this issue was already resolved. See https://github.com/giswqs/whiteboxR/issues/32#issuecomment-875233755
```
devtools::install_github("giswqs/whiteboxR")
```

**Comment by tcalegario** [comment]
That works fine!

Thanks a lot.

I used 

`install.packages("whitebox", repos="http://R-Forge.R-project.org")`

best wishes
