### ISSUE TITLE
Github installation issue with whiteboxR 1.5.1

### ISSUE THREAD

**Issue by bkielstr** [giswqs/whiteboxR#40]
whiteboxR 1.5.1 is failing to install on a fresh R 4.1.0 and RStudio 1.4.1717 on both Mac and Windows. The error messages are different but likely related a namespace issue. 

*********
Windows: 

devtools::install_github("giswqs/whiteboxR") # For latest version
Downloading GitHub repo giswqs/whiteboxR@HEAD
√  checking for file 'C:\Users\bkielstr\AppData\Local\Temp\Rtmp8OkmWJ\remotes9141fb76178\giswqs-whiteboxR-439e248/DESCRIPTION' (666ms)
-  preparing 'whitebox': (2.3s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (15s)
-  checking for empty or unneeded directories
   Removed empty directory 'whitebox/PY2R'
   Removed empty directory 'whitebox/docs'
   Removed empty directory 'whitebox/misc'
-  building 'whitebox_1.5.1.tar.gz'
   
* installing *source* package 'whitebox' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'whitebox'
    finding HTML links ... done" 
    
    ... 
    
    ** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'whitebox':
 .onLoad failed in loadNamespace() for 'whitebox', details:
  call: apply(sapply(token_patterns, function(x) grepl(x, res), simplify = FALSE), 
  error: dim(X) must have a positive length
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'whitebox':
 .onLoad failed in loadNamespace() for 'whitebox', details:
  call: apply(sapply(token_patterns, function(x) grepl(x, res), simplify = FALSE), 
  error: dim(X) must have a positive length
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/R-4.1.0/library/whitebox'

Session info: 

R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.1     devtools_2.4.2    pkgload_1.2.1     R6_2.5.0          rlang_0.4.11     
 [8] fastmap_1.1.0     tools_4.1.0       pkgbuild_1.2.0    sessioninfo_1.1.1 cli_3.0.1         withr_2.4.2       ellipsis_0.3.2   
[15] remotes_2.4.0     rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.2    purrr_0.3.4       callr_3.7.0      
[22] fs_1.5.0          ps_1.6.0          testthat_3.0.4    curl_4.3.2        memoise_2.0.0     glue_1.4.2        cachem_1.0.5     
[29] compiler_4.1.0    desc_1.3.0        prettyunits_1.1.1

******* 

Mac: 

devtools::install_github("giswqs/whiteboxR")
Downloading GitHub repo giswqs/whiteboxR@HEAD
✓  checking for file ‘/private/var/folders/z9/cqjtj3ln135_79r_4cbpc15c0000gn/T/RtmpdvcGRc/remotes53be275b60cb/giswqs-whiteboxR-439e248/DESCRIPTION’ (374ms)
─  preparing ‘whitebox’: (724ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (1.1s)
─  checking for empty or unneeded directories
   Removed empty directory ‘whitebox/PY2R’
   Removed empty directory ‘whitebox/docs’
   Removed empty directory ‘whitebox/misc’
─  building ‘whitebox_1.5.1.tar.gz’
   
* installing *source* package ‘whitebox’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘whitebox’:
 .onLoad failed in loadNamespace() for 'whitebox', details:
  call: NULL
  error: C stack usage  7970516 is too close to the limit
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/whitebox’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/z9/cqjtj3ln135_79r_4cbpc15c0000gn/T//RtmpdvcGRc/file53be602fc39c/whitebox_1.5.1.tar.gz’ had non-zero exit status

Session info: 

R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.4.2 usethis_2.0.1 

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    pkgload_1.2.1     R6_2.5.0          rlang_0.4.11     
 [6] fastmap_1.1.0     tools_4.1.0       pkgbuild_1.2.0    sessioninfo_1.1.1 cli_3.0.1        
[11] withr_2.4.2       ellipsis_0.3.2    remotes_2.4.0     rprojroot_2.0.2   lifecycle_1.0.0  
[16] crayon_1.4.1      processx_3.5.2    purrr_0.3.4       callr_3.7.0       fs_1.5.0         
[21] ps_1.6.0          curl_4.3.2        testthat_3.0.4    memoise_2.0.0     glue_1.4.2       
[26] cachem_1.0.5      compiler_4.1.0    desc_1.3.0        prettyunits_1.1.1

**Comment by brownag** [comment]
This is running afoul of the (bad) heuristics I was using to find the whitebox binary. I actually think we should not use the method I put in there. I will remove it and have you try and install without it off a branch.

**Comment by brownag** [comment]
Try this. Will merge in if it works. I am glad this came up, because I knew that method was over-doing it and needed to be removed/re-thought.
```r
remotes::install_github("giswqs/whiteboxR@fix-findwhitebox", dependencies=FALSE)
```

**Comment by bkielstr** [comment]
Smooth installation for both operating systems!
