### ISSUE TITLE
wbt_stochastic_depression_analysis

### ISSUE THREAD

**Issue by Bern67** [giswqs/whiteboxR#54]
Hello - I just installed the whiteboxR package and tried to run two separate DEM's (.tif) and keep getting the same error:

library(raster)
library(whitebox)

> demP1 <- raster("D:/R Projects/P1Karst/data/dtm.tif")
> rm(dem,output)
> wbt_stochastic_depression_analysis(
+   demP1,
+   output="D:/R Projects/P1Karst/data/p1pdep.tif", #pdep=probability of depression output to working directory
+   rmse=0.05, # Point cloud error, in meters
+   range=4, #size of pixel (at least 3X resolution of DEM)
+   iterations = 300, # Play with 100-500 to start
+   wd = "D:/R Projects/P1Karst",
+   verbose_mode = F,
+   compress_rasters = FALSE
+ )

Error running WhiteboxTools (stochastic_depression_analysis)
  whitebox.exe_path: "C:/Users/h2obe/Documents/R/win-library/4.1/whitebox/WBT/whitebox_tools.exe"; File exists? TRUE
  Arguments: --run=stochastic_depression_analysis  --dem=raster(ncols=11168, nrows=15633, xmn=786533, xmx=820037, ymn=351145, ymx=398044, crs='+proj=utm +zone=10 +datum=NAD83 +units=m +no_defs') --output=D:/R Projects/P1Karst/data/p1pdep.tif --rmse=0.05 --range=4 --iterations=300 --wd=D:/R Projects/P1Karst -v

System command had status 101
stochastic_depression_analysis - Elapsed Time: NA [did not run]

The DEMs are 1-m LiDAR downloaded from public server.
Does the dem need to be in a specific format to work in whiteboxR?

FYI, I ran the following code and it works just fine:
dem <- system.file("extdata", "DEM.tif", package = "whitebox")

wbt_stochastic_depression_analysis(
  dem,
  output="D:/R Projects/P1Karst/data/test.tif", #pdep=probability of depression output to working directory
  rmse=0.05, # in meters
  range=4, # size of pixel (at least 3X resolution of DEM)
  iterations = 300, # Play with 100-500 to start
  wd = "D:/R Projects/P1Karst/data",
  verbose_mode = F,
  compress_rasters = FALSE
)

Thus, makes me think the dem format needs to be very specific.

**Comment by giswqs** [comment]
The input should be a file path to the geotiff, not a raster object.

**Comment by Bern67** [comment]
Same result

**Comment by Bern67** [comment]
demP1 <- "D:/R Projects/P1Karst/data/dtm_utmZ10.tif"

**Comment by giswqs** [comment]
Then it might be the problem of the GeoTIFF. See https://github.com/jblindsay/whitebox-tools/issues/23

**Comment by Bern67** [comment]
OK, got it, the current version of whiteboxR does not work with geotiff and there is no documentation for how to get a dem to work in witeboxR.

**Comment by brownag** [comment]
> OK, got it, the current version of whiteboxR does not work with geotiff and there is no documentation for how to get a dem to work in witeboxR.

@Bern67 as you demonstrated the tool works fine with the sample GeoTIFF DEM provided in the package. Most of our examples and vignettes for whiteboxR use this GeoTIFF DEM.

For starters could you provide the output of `gdalinfo` run on the raster(s) in question? See https://gdal.org/programs/gdalinfo.html / `gdalUtils::gdalinfo()`


```r
gdalUtils::gdalinfo("path/to/your/file.tif")
```

For instance: 
``` r
gdalUtils::gdalinfo(system.file("extdata", "DEM.tif", package = "whitebox")) |> paste0("\n") |> cat()
#> Driver: GTiff/GeoTIFF
#>  Files: C:/Users/Andrew.G.Brown/Documents/R/win-library/4.1/whitebox/extdata/DEM.tif
#>  Size is 237, 188
#>  Coordinate System is:
#>  LOCAL_CS["unnamed",
#>      UNIT["unknown",1]]
#>  Origin = (664692.058977327193134,4895827.599877157248557)
#>  Pixel Size = (89.983495661721150,-90.021537309324245)
#>  Metadata:
#>    AREA_OR_POINT=Point
#>    TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
#>    TIFFTAG_SOFTWARE=GoSpatial
#>    TIFFTAG_XRESOLUTION=72
#>    TIFFTAG_YRESOLUTION=72
#>  Image Structure Metadata:
#>    INTERLEAVE=BAND
#>  Corner Coordinates:
#>  Upper Left  (  664692.059, 4895827.600) 
#>  Lower Left  (  664692.059, 4878903.551) 
#>  Upper Right (  686018.147, 4895827.600) 
#>  Lower Right (  686018.147, 4878903.551) 
#>  Center      (  675355.103, 4887365.575) 
#>  Band 1 Block=237x1 Type=Float32, ColorInterp=Gray
#>    NoData Value=-32768
```

I would be happy to take a closer look at this if you can give a sample DEM/source that has this problem

**Comment by brownag** [comment]
I am closing this as it appears the tool works as expected.
@Bern67: if you have a sample DEM that can reproduce this issue feel free to respond here or open a new issue.

**Comment by brownag** [comment]
@Bern67 If any of your file paths include spaces, please try using `shQuote()` or surrounding them with single quotes. This may be the source of your problems.
