### ISSUE TITLE
Weighted flow accumulation

### ISSUE THREAD

**Issue by tcalegario** [giswqs/whiteboxR#56]
Dear giswqs,

hope you are well. 

Thanks for this package. It's awesome.

I'm wondering if I can make a weighted flow accumulation with this package.

For example, I would like to obtain mean rainfall in all flow accumulation pixels which represents "mean rainfall" in all 'catchment area' (https://www.researchgate.net/publication/348961247_Gauging_the_Ungauged_Regionalization_of_Flow_Indices_at_Grid_Level)

Thanks a lot for your attention.

Best wishes.

**Comment by jblindsay** [comment]
Please see the [DInfMassFlux](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#DInfMassFlux) and the [D8MassFlux](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#D8MassFlux) tools.

**Comment by tcalegario** [comment]
Thanks jblindsay!

**Comment by jblindsay** [comment]
No problem @tcalegario. Also, just for future reference, questions/issues like this should probably be issued to the [WhiteboxTools backend](https://github.com/jblindsay/whitebox-tools) rather than the R front-end.
