### ISSUE TITLE
Error when calling whitebox::tool

### ISSUE THREAD

**Issue by jpshanno** [giswqs/whiteboxR#6]
Hi, thanks for the work on this package, it's a great resource! I was trying it out on a problem today and found that if you call a function with out loading the library, e.g. `whitebox::idw_interpolation`, the system call that gets created errors out. It looks like the problem is here in the function code: 
```
tool_name <- match.call()[[1]]
```
which doesn't remove the 'whitebox::' from the tool name. I created this workaround that seemed to fix the problem, I think putting this into ```wbt_run_tool()``` would solve the problem for most (all?) of the tools.
```
tool_name <- as.character(match.call()[[1]])  
tool_name <- tool_name[!grepl("(whitebox|::)", tool_name)]
```

**Comment by giswqs** [comment]
@jpshanno Many thanks for reporting the issue and providing the sample solution! I have updated the package with your solution. I believe the errors have been fixed for all the tools. You can install the latest update from GitHub using the code below. I will update the package on [R-Forge](https://r-forge.r-project.org/R/?group_id=2337) shortly. However, I don't when the CRAN package will get updated. I submitted it to CRAN two weeks ago, and it is still [under review](https://cransays.itsalocke.com/articles/dashboard.html). 

```
if (!require(devtools)) install.packages('devtools')
devtools::install_github("giswqs/whiteboxR")
```
