### ISSUE TITLE
wbt_watershed returns System command had status 101

### ISSUE THREAD

**Issue by Nischal-Karki-ATW** [giswqs/whiteboxR#61]
I am using wbt to delineate watershed. I have flow direction and flow accumulation grid from [MERIT-Hydro](https://developers.google.com/earth-engine/datasets/catalog/MERIT_Hydro_v1_0_1). I test for one pour point, after extracting stream from flow accumulation and snap pour point to stream. I also cross-checked the snapped pour point and it lies in the stream pixel. 
The code is:
```
wbt_watershed(d8_pntr = "E:/Project/flow_dir.tif",
pour_pts = "E:/Project/snappedpp.shp",
output = "E:/watersheds.tif")
```
Could it be because of the flow direction file? The Data type of flow direction grid is: Byte - Eight bit unsigned integer.

**Comment by giswqs** [comment]
Please provide the details for the error.

**Comment by Nischal-Karki-ATW** [comment]
```
Error running WhiteboxTools (watershed)
  whitebox.exe_path: "C:/Users/asus/Documents/R/win-library/4.1/whitebox/WBT/whitebox_tools.exe"; File exists? TRUE
  Arguments: --run=watershed  --d8_pntr=E:/Project/flow_dir.tif --pour_pts=E:/Project/snappedpp.shp --output=E:/watersheds.tif -v

System command had status 101
watershed - Elapsed Time: NA [did not run]
```
This is all I got.

**Comment by tcalegario** [comment]
I think the result raster and st_read may help.

```
raster("E:/Project/flow_dir.tif")
st_read("E:/Project/snappedpp.shp")
```
