### ISSUE TITLE
Line across hillshade output

### ISSUE THREAD

**Issue by jflowernet** [giswqs/whiteboxR#66]
Hi,
First thanks for the excellent package. These tools are very useful.

I'm a total beginner with whitebox, but have a problem with hillshade that I can't resolve and am hoping someone can help with. There is a line across the hillshade output and I don't understand where it is coming from as there doesn't seem to be anything in the DEM that would result in this. The DEM and resulting hillshade are:

![image](https://user-images.githubusercontent.com/17166483/159841400-2d7506a4-e7f8-4590-af3d-d8e0131c1a53.png)

Code (tif attached):

```
library(terra)
library(tmap)
library(whitebox)

wbt_init(exe_path = file.path("WBT", "whitebox_tools"))

data_folder <- "data"

dem <- rast(file.path(data_folder, "dem.tif"))

wbt_hillshade(dem = file.path(data_folder, "dem.tif"),
              output = file.path(data_folder, "hillshade.tif"))

hillshade <- rast(file.path(data_folder, "hillshade.tif"))

tm1 <- tm_shape(dem)+
  tm_raster(style = "cont", palette = "BrBG", title = "Height (m)") +
  tm_graticules() +
  tm_layout(legend.outside = TRUE, panel.labels = "DEM") 

tm2 <- tm_shape(hillshade)+
  tm_raster(style = "cont", palette = "-Greys", title = "Hillshade")+
  tm_graticules() +
  tm_layout(legend.outside = TRUE, panel.labels = "Hillshade")

tmap_arrange(tm1, tm2, nrow = 2)
```
[dem.tif.zip](https://github.com/giswqs/whiteboxR/files/8338417/dem.tif.zip)

**Comment by brownag** [comment]
Thanks for reporting this issue. Interesting. It appears you can get around this by first projecting your DEM into something other than EPSG:4326. Here's an example projecting to [EPSG:32643](https://spatialreference.org/ref/epsg/wgs-84-utm-zone-43n/)

``` r
library(terra)
#> terra 1.5.23
library(tmap)
library(whitebox)

data_folder <- path.expand("~/data")
dir.create(data_folder, showWarnings = FALSE, recursive = TRUE)
wbt_init(exe_path = wbt_exe_path(), wd = data_folder)

if (!file.exists(file.path(data_folder, "dem.tif"))) {
  download.file(
    "https://github.com/giswqs/whiteboxR/files/8338417/dem.tif.zip",
    destfile = file.path(data_folder, "dem.tif.zip")
  )
  unzip(file.path(data_folder, "dem.tif.zip"), exdir = data_folder)
}

# geographic CRS (EPSG:4326)
dem <- rast(file.path(data_folder, "dem.tif"))

# projected CRS
dem2 <- writeRaster(project(dem, "EPSG:32643"), file.path(data_folder, "dem2.tif"), overwrite = TRUE)

wbt_hillshade(dem = "dem.tif", output = "hillshade.tif")
wbt_hillshade(dem = "dem2.tif", output = "hillshade2.tif")

hillshade1 <- rast(file.path(data_folder, "hillshade.tif"))
hillshade2 <- rast(file.path(data_folder, "hillshade2.tif"))

tm1 <- tm_shape(hillshade1)+
  tm_raster(style = "cont", palette = "BrBG", title = "Height (m)") +
  tm_graticules() +
  tm_layout(legend.outside = TRUE, panel.labels = "Hillshade (EPSG:4326)") 

tm2 <- tm_shape(hillshade2)+
  tm_raster(style = "cont", palette = "-Greys", title = "Hillshade")+
  tm_graticules() +
  tm_layout(legend.outside = TRUE, panel.labels = "Hillshade (EPSG:32643)")

tmap_arrange(tm1, tm2, nrow = 2)
```

![](https://i.imgur.com/iteCkme.png)

As far as I can tell this doesn't affect _all_ hillshades done on rasters with a geographic CRS, at least repeating the above example with the sample DEM in whitebox in EPSG:26918 and EPSG:4326 does not show the same effect. The `terra::terrain()` derivatives all look reasonable with your EPSG:4326 DEM as input, and so do simpler tools output such as `wbt_slope()`. There could be some sort of interaction between your DEM and the hillshade algorithm...

At any rate, we won't be can't do much about this in the whiteboxR package repository as the R package is just a wrapper around the Rust library: https://github.com/jblindsay/whitebox-tools/issues. You might consider having them take a look at the DEM

**Comment by jflowernet** [comment]
Many thanks for the quick response and the workaround @brownag! Strange that this particular DEM has a problem being in 4326 for hillshade and others do not. I had run the sample DEM without problems as you said, so I had discounted the projection as the issue.

I'll post an issue in whitebox tools just in case there is some odd bug in the code. 

Thanks again!
