### ISSUE TITLE
status 101 when trying to use whitebox in R (windows)

### ISSUE THREAD

**Issue by geoendemics** [giswqs/whiteboxR#7]
Dear Wu
I downloaded the whitebox package for R on a windows machine. Everytime,  I try to run a function i R I keep getting this error

[2] "* Welcome to FeaturePreservingDenoise *"                                                                
[3] "***************************************"                                                                
[4] "Reading data..."                                                                                        
[5] "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\\libcore\\option.rs:355:21"
[6] "note: Run with `RUST_BACKTRACE=1` for a backtrace."                                                     
attr(,"status")
[1] 101

Any idea what  is wrong? .  Any help would appreciated
Rengifo

**Comment by giswqs** [comment]
What raster data format are you using? I just tested the `FeaturePreservingDenoise` tool using the following code without any problem. Could you also try the following sample code to see if it can run successfully? If this sample code works fine, then the error your reported was probably caused by your raster data. 

Sample code:
```
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package="whitebox")
output <- file.path(getwd(), "output.tif")
feature_preserving_denoise(dem, output, filter=9, verbose_mode = FALSE)
```
Output:
`[1] "feature_preserving_denoise - Elapsed Time (excluding I/O): 0.709s"`

**Comment by geoendemics** [comment]
> What raster data format are you using? I just tested the `FeaturePreservingDenoise` tool on Windows using the following code without any problem. Could you also try the following sample code to see if it can run successfully? If this sample code works fine, then the error your reported was probably caused by your raster data.
> 
> Sample code:
> 
> ```
> library(whitebox)
> dem <- system.file("extdata", "DEM.tif", package="whitebox")
> output <- file.path(getwd(), "output.tif")
> feature_preserving_denoise(dem, output, filter=9, verbose_mode = FALSE)
> ```
> Output:
> `[1] "feature_preserving_denoise - Elapsed Time (excluding I/O): 0.709s"`


Thanks for  your response
I am going to give a try the next days. Sorry for late response. was busy with other projects.

**Comment by geoendemics** [comment]
Dear Wu
Thanks a lot for  your quick response. I run the command as you  explained and it worked smoothly. Still, I have a question. The syntax  refers to the  **system.file** function. Does it mean that my input files  always have to be placed at "the extdata" to be able to access the whitebox package.?
Best regards
Rengifo

**Comment by giswqs** [comment]
@geoendemics The input files can be from any file paths. 

`dem <- "/path/to/whatever.tif"`

**Comment by geoendemics** [comment]
thanks Wu ! 
I am pretty new to R.
Rengifo

**Comment by giswqs** [comment]
@geoendemics Glad to hear that this issue has been resolved. Feel free to open new issues if you encounter problems with the whitebox R package.

**Comment by geoendemics** [comment]
> @geoendemics Glad to hear that this issue has been resolved. Feel free to open new issues if you encounter problems with the whitebox R package.

Dear Wu, Finally I go the impoundment index working in Arcgis 10.6,  but  in R I get the following error: 
Warning message:
In system(args2, intern = TRUE) :
  running command '\\nve.no/fil/home/rzo/Dokumenter/R/win-library/3.5/whitebox/WBT/whitebox_tools.exe --run=impoundment_index  --dem=N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/utvikDTM.tif --output=N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/impoundmentDTMutvik.tif --damlength=20 --out_type=depth -v' had status 101

 this is the syntax I used **impoundment_index(dem, output,damlength=20, out_type = "depth",verbose_mode = TRUE)**
thanks in advance
Rengifo

**Comment by giswqs** [comment]
@geoendemics I guess you are using an outdated version of whiteboxR. The impoundment function has been changed to `impoundment_size_index()`. Please run the following code to upgrade the package.  

```
remove.packages("whitebox")
devtools::install_github("giswqs/whiteboxR")
whitebox::wbt_init()
library(whitebox)
dem <- "N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/utvikDTM.tif"
output <- "N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/impoundmentDTMutvik.tif"
impoundment_size_index(dem, output,damlength=20, out_type = "depth",verbose_mode = TRUE)
```

**Comment by geoendemics** [comment]
@giswqs 
thanks a lot for your support I tried whiteboxR in both, linux and windows and they both worked  perfectly. By the way much quicker than ArcGIS.

**Comment by estebangatillo** [comment]
Hi, I'm having this same problem! I've followed all the directions here, uninstalled/reinstalled whitebox, tried different machines - no luck. I'm trying to run the `wbt_d8_pointer` tool on a normail .tif raster.

Here's my code:
```
remove.packages("whitebox")
devtools::install_github("giswqs/whiteboxR")
whitebox::wbt_init()
library(whitebox)
dem <- raster("D:/whitebox/dem.tif")
output <- "D:/whitebox/d8_test.tif"
d8_test <- wbt_d8_pointer(dem10, output, esri_pntr = TRUE, verbose_mode = TRUE)
d8_test
```
Here are the results:
`> d8_test <- wbt_d8_pointer(dem10, output, esri_pntr = TRUE, verbose_mode = TRUE)
Warning message:
In system(args2, intern = TRUE) :
  running command 'C:/Users/esteb/Documents/R/win-library/3.6/whitebox/WBT/whitebox_tools.exe --run=d8_pointer  --dem=raster(ncol=11646, nrow=10757, xmn=-122.359444446, xmx=-121.281111114, ymn=44.711666661, ymx=45.707685178, crs='+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs') --output=D:/whitebox/d8_test.tif --esri_pntr -v' had status 101
> d8_test
[1] "thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\\src\\libcore\\slice\\mod.rs:2715:10"
[2] "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace."                                                                                        
attr(,"status")
[1] 101`

Any ideas greatly appreciated, thank you!

**Comment by jblindsay** [comment]
@estebangatillo Yes, I'm aware of this issue. In my attempt to fix the library, specifically tools with Boolean parameters, to handle the case of --flag=False, I broke the case of --flag=True. I've actually already posted a fix for this in the WhiteboxTools repository. The fix for the R front-end will require that I publish v1.0.2. I'm hoping to do so either today or tomorrow. I'm very sorry for the inconvenience.

**Comment by giswqs** [comment]
@estebangatillo Thanks to Dr. John Lindsay's [WhiteboxTools v1.0.2 release](https://github.com/jblindsay/whitebox-tools/releases/tag/v1.0.2), I have updated the [whitebox R package](https://github.com/giswqs/whiteboxR/commit/4d87ee7bcae349c3ebf99d471c70afc331eea221) accordingly. Please update your R package and try again. I tested your code. It works now.

**Comment by estebangatillo** [comment]
Thanks you @giswqs and @jblindsay for the help! Unfortunately, even with 1.0.2 I'm still getting the same error.
```
> library(whitebox)
> dem <- raster("D:/whitebox/dem.tif")
> output <- "D:/whitebox/fill_test.tif"
> wbt_fill_depressions(dem, output, fix_flats = TRUE, verbose_mode = FALSE)
[1] "fill_depressions - note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace."
Warning message:
In system(args2, intern = TRUE) :
  running command 'C:/Users/esteb/Documents/R/win-library/3.6/whitebox/WBT/whitebox_tools.exe --run=fill_depressions  --dem=raster(ncol=11646, nrow=10757, xmn=-122.359444446, xmx=-121.281111114, ymn=44.711666661, ymx=45.707685178, crs='+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs') --output=D:/whitebox/fill_test.tif --fix_flats -v' had status 101
```
Just to be sure I'm using the right version:
```
> print(wbt_version())
[1] "WhiteboxTools v1.0.2 by Dr. John B. Lindsay (c) 2017-2019"                  
[2] ""                                                                           
[3] "WhiteboxTools is an advanced geospatial data analysis platform developed at"
[4] "the University of Guelph's Geomorphometry and Hydrogeomatics Research "     
[5] "Group (GHRG). See https://jblindsay.github.io/ghrg/WhiteboxTools/index.html"
[6] "for more details."
```  
Do you have any other troubleshooting recommendations? Perhaps I need a specific GCS?
Thanks again.

**Comment by jblindsay** [comment]
@estebangatillo I haven't used the R frontend extensively but I don't believe you can specify an R 'raster' (dem in your case) as an input parameter to a WhiteboxTools function. It should just take in a string. Please see [here](https://jblindsay.github.io/wbt_book/r_interface.html)

**Comment by giswqs** [comment]
Could you try the following example? I just tried it on both Windows and Linux, it works fine. As John mentioned, file input to a WhiteboxTools function should be a file path, not an R raster. 

```
library(whitebox)

# Set input raster DEM file
dem <- system.file("extdata", "DEM.tif", package = "whitebox")

# Run tools
wbt_feature_preserving_smoothing(dem, "./smoothed.tif", filter = 9, verbose_mode = TRUE)
wbt_fill_depressions(dem, "./filled.tif", fix_flats = TRUE, verbose_mode = FALSE)
```

**Comment by estebangatillo** [comment]
I was having projection issues with my dem, I corrected the issue, ran the tools and got a result! Thank you for the help. However, output from streamslopecontinuous has values ranging from -88 to 89. I'm trying to figure out how to interpret these values and/or what I did wrong. I used FlowAccumulationFullWorkflow to generate the input rasters for streamslopecontinuous. I used extractstreams for the stream input raster. The dem used to run the tools is in meters. Perhaps this needs to be in different units? Thank you both mucho!

```
> setMinMax(streamslope2)
class      : RasterLayer 
dimensions : 5379, 5823, 31321917  (nrow, ncol, ncell)
resolution : 0.0001851795, 0.0001851682  (x, y)
extent     : -122.3594, -121.2811, 44.71167, 45.70769  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 
source     : D:/whitebox/stream_slope.tif 
names      : stream_slope 
values     : -88.22954, 88.92815  (min, max)

> dem10
class      : RasterLayer 
dimensions : 10757, 11646, 125276022  (nrow, ncol, ncell)
resolution : 9.259259e-05, 9.259259e-05  (x, y)
extent     : -122.3594, -121.2811, 44.71167, 45.70769  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs 
source     : D:/bark_beaver_project/dem10.tif 
names      : dem10 
values     : 2.139266, 3426.342  (min, max)
```

**Comment by giswqs** [comment]
@estebangatillo It seems your issue is no longer caused by the R front-end. I would suggest you [open an issue on the whitebox-tools repo](https://github.com/jblindsay/whitebox-tools/issues) so that Dr. John Lindsay can further investigate the issue when he has time.

**Comment by reesemcardle** [comment]
WhiteboxTools binary is located at:  /Library/Frameworks/R.framework/Versions/3.6/Resources/library/whitebox/WBT/whitebox_tools 
You can now start using whitebox
    > library(whitebox)
    > wbt_version()
> library(whitebox)
> dem <- "N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/utvikDTM.tif"
> output <- "N:/Prosjekter/Elvevifter/6_data_c/FinalDTM/impoundmentDTMutvik.tif"
> impoundment_size_index(dem, output, damlength=20, out_type = "depth",verbose_mode = TRUE)
Error in impoundment_size_index(dem, output, damlength = 20, out_type = "depth",  : 
  could not find function "impoundment_size_index"
> wbt_version()
[1] "WhiteboxTools v1.1.0 by Dr. John B. Lindsay (c) 2017-2019"                  
[2] ""                                                                           
[3] "WhiteboxTools is an advanced geospatial data analysis platform developed at"
[4] "the University of Guelph's Geomorphometry and Hydrogeomatics Research "     
[5] "Group (GHRG). See https://jblindsay.github.io/ghrg/WhiteboxTools/index.html"
[6] "for more details."                                                          
>

**Comment by giswqs** [comment]
Since the last release, all WBT functions in R now have a prefix `wbt_`, so please call the function using `wbt_impoundment_size_index()`

**Comment by junzhang55** [comment]
I've got the same error of status 101 as shown below and tried all the solution in this page but still got the error. I'm using the newest whitebox "WhiteboxTools v1.3.0 by Dr. John B. Lindsay (c) 2017-2019". 

> wbt_feature_preserving_smoothing("./250mPF_DEMmin_NA.tif","./250mPF_DEM_WBSmoothed_test13.tif", filter = 20, norm_diff = 15, num_iter = 3, max_diff = 5, zfactor = 1, verbose_mode = FALSE) 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "Invalid code 202, expected code <= 1FF" }', src/raster/geotiff/mod.rs:1113:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1] "feature_preserving_smoothing - Reading data..."
Warning message:
In system(args2, intern = TRUE) :
  running command '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/whitebox/WBT/whitebox_tools --run=feature_preserving_smoothing  --dem=./250mPF_DEMmin_NA.tif --output=./250mPF_DEM_WBSmoothed_test13.tif --filter=20 --norm_diff=15 --num_iter=3 --max_diff=5 --zfactor=1 -v' had status 101

When I tried dem <- system.file("extdata", "250mPF_DEMmin_NA.tif", package="whitebox"), I've got dem="", which I think is not right. The wbt_feature_preserving_smoothing worked well with my 1km dem raster but not 250m, which is wired because 1km raster was aggregated from 250m raster.

Is there any suggestions about this issue?
Thanks.

**Comment by giswqs** [comment]
@junzhang55 Try the following script to see if it works. If yes, that mean you did not specify the file path correctly. Try using absolute path rather than relative path with `./`

```
library(whitebox)
DEM <- system.file("extdata", "DEM.tif", package = "whitebox")
output <- file.path(getwd(), "DEMsmooth.tif")
wbt_feature_preserving_smoothing(DEM, output, filter = 7, norm_diff = 15, num_iter = 10, verbose_mode = TRUE)
```

**Comment by junzhang55** [comment]
Thanks for the quick reply! However, the error still exists, here is the outputs. Even with the full path DEM <- system.file("extdata", "/Users/junzhang/Documents/Topography/Grid_setup/250m/250mPF_DEMmin_NA.tif",package = "whitebox"), I still got DEM="".

> library(whitebox)
> DEM <- system.file("extdata", "/Users/junzhang/Documents/Topography/Grid_setup/250m/250mPF_DEMmin_NA.tif",package = "whitebox")
> output <- file.path(getwd(), "DEMsmooth.tif")
> wbt_feature_preserving_smoothing(DEM, output, filter = 7, norm_diff = 15, num_iter = 10, verbose_mode = TRUE)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/raster/mod.rs:1261:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1] "*****************************************" "* Welcome to FeaturePreservingSmoothing *"
[3] "*****************************************" "Reading data..."                          
attr(,"status")
[1] 101
Warning message:
In system(args2, intern = TRUE) :
  running command '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/whitebox/WBT/whitebox_tools --run=feature_preserving_smoothing  --dem= --output=/Users/junzhang/Documents/Topography/Grid_setup/250m/DEMsmooth.tif --filter=7 --norm_diff=15 --num_iter=10 --max_diff=0.5 --zfactor=1 -v' had status 101

**Comment by giswqs** [comment]
You should not use `system.file()`. That's for finding the package sample data location. Simply use 
`DEM <- "/Users/junzhang/Documents/Topography/Grid_setup/250m/250mPF_DEMmin_NA.tif"`

**Comment by junzhang55** [comment]
It's still the same. I'm using macOS Mojave, does it matter with systems?

> DEM <- "/Users/junzhang/Documents/Topography/Grid_setup/250m/250mPF_DEMmin_NA.tif"
> output <- file.path(getwd(), "DEMsmooth.tif")
> wbt_feature_preserving_smoothing(DEM, output, filter = 7, norm_diff = 15, num_iter = 10, verbose_mode = TRUE)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "Invalid code 202, expected code <= 1FF" }', src/raster/geotiff/mod.rs:1113:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1] "*****************************************" "* Welcome to FeaturePreservingSmoothing *" "*****************************************"
[4] "Reading data..."                          
attr(,"status")
[1] 101
Warning message:
In system(args2, intern = TRUE) :
  running command '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/whitebox/WBT/whitebox_tools --run=feature_preserving_smoothing  --dem=/Users/junzhang/Documents/Topography/Grid_setup/250m/250mPF_DEMmin_NA.tif --output=/Users/junzhang/Documents/Topography/Grid_setup/250m/DEMsmooth.tif --filter=7 --norm_diff=15 --num_iter=10 --max_diff=0.5 --zfactor=1 -v' had status 101

**Comment by giswqs** [comment]
The error you encountered was probably caused by your GeoTIFF file. Try converting the GeoTIFF to other formats, such as ESRI (ArcGIS) ASCII and binary (.flt & .hdr). Hopefully it will resolve the issue.

See https://github.com/jblindsay/whitebox-tools/issues/98

**Comment by junzhang55** [comment]
Thanks, I will give a shot.

**Comment by junzhang55** [comment]
Hi Dr Wu, you're right! It's the format problem, I simply changed my GeoTiff to float64 and it worked! Although I don't know why it doesn't work with float32, I'm still very happy to have the problem solved. Thanks for your help!!!

**Comment by jblindsay** [comment]
I've run into this same "Invalid code 202, expected code <= 1FF" error myself recently. I've tracked it down to the LZW compression library that I use in WhiteboxTools' GeoTIFF reader. I'll see what I can do to fix it. Once again, the GeoTIFF file format, in all its horrible complexity, has become the bane of my existence. I need to support GeoTIFFs in WBT because it is ubiquitous, but at the same time, a developer team of one person can't possibly handle all of the odd corner-cases of this extremely complex and flexible file format. In the meantime, I would suggest saving files using the DEFLATE method rather than LZW. The 32-bit versus 64-bit floating point issue shouldn't matter.

**Comment by giswqs** [comment]
@jblindsay I totally agree with you. It would be an enormous task to implement everything from scratch in order to provide full support for GeoTIFF. Users can use GDAL or other third-party libraries/packages to convert data format from time to time if needed.
