### ISSUE TITLE
TimeInDaylight not working on a full DSM tile

### ISSUE THREAD

**Issue by megalulu** [giswqs/whiteboxR#82]
Hello, 
I am using the whitebox tool Time In Daylight with a digital surface model tile located in Quebec. I need to know where shading from overhanging vegetation on a river occurs when the sun is at it's heightest point in the sky(about 11h45) on the longest day (june 21st).  I am running the algorithm through the terminal on a windows computer. 
The parameters I am using are :
input = DEM tile (path towards DEM tile)
output  = path towards output file
az_fraction = 30.0
max_dist = 100.0
lat=45.9397013082792
long=-71.6258803600092
utc_offset=-05:00
start_day=172
end_day=172
tart_time=09:45
end_time=14:00

These parameters give me a coherent output (raster with values between 0 and 1) when I run it on a subset of the DSM tile. I've tried 4 different subsets of varying size (one very close to the original tile size).  However, when I run the algorithm with the exact same parameters on the entire DSM tile, the output is a raster full of NAs. 
I've tried subsetting to the extent of the tile, and still the results are not coherent (raster full of NA) 
I have managed to run the algorithm on the entire tile, but for a longer periode of time, but the computation takes a long time, so I would to reduce the window of time in which I'm running the algorithm.

Is there anyway you could help me with this problem. 
I can provide the DSM tile if needed. 

Thank you very much.

Meghana

**Comment by brownag** [comment]
Hi Meghana,

It would be helpful if you could provide the tile or the minimal amount of a tile to reproduce the problem. Does the tool make any additional output in terminal? How large is the full file? 

Also, this is probably not related to the WhiteboxTools R frontend (https://github.com/giswqs/whiteboxR) if you are encountering the problem while running whitebox from the terminal. It would be best to bring this issue up (with data to reproduce the issue) on https://github.com/jblindsay/whitebox-tools/issues

**Comment by megalulu** [comment]
Hello Andrew, 

Thanks for your response. I will post the problem in the right github issues page with the tile in quesiton. 

Meghana
