### ISSUE TITLE
whiteboxR memory allocation

### ISSUE THREAD

**Issue by geoendemics** [giswqs/whiteboxR#9]
Hi  Guys , I hope you had a nice eastern.  I tried the slope tool in R and got the message below.  I am trying to calculate the slope of a very large DEM (75 735 714 kb). Is there a work around for this problem.?
thanks in advance

slope(dem, output,zfactor=1, verbose_mode = TRUE)
[1] "********************"                          "* Welcome to Slope *"                         
[3] "********************"                          "Reading data..."                              
[5] "memory allocation of 77553370898 bytes failed"
attr(,"status")
[1] 1033

**Comment by jblindsay** [comment]
@geoendemics If the size of your data in memory and with all of the temporary rasters that are stored (in the case of the Slope tool, you need to have the input DEM and output file in memory, both represented as 64-bit floats) exceeds the RAM of your computing system, you will have a memory allocation issue. Your DEM is 75 GB in size, and is likely storing elevations as 32-bit floats. So, you will need at least 2x75*2=300 GB of memory to be able to process this file. You're DEM is way too big to process on most computers. You'll either need to increase your RAM, find a computer that has sufficient RAM, cut your DEM into smaller tiles, or decrease the resolution of your DEM.
